CREATE TABLE [dbo].[TBARRONDISSEMENT](
	[IDARRONDISSEMENT] [int] NOT NULL,
	[LIBARRONDISSEMENT] [varchar](50) NULL,
 CONSTRAINT [PK_TBARRONDISSEMENT] PRIMARY KEY CLUSTERED 
(
	[IDARRONDISSEMENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]