CREATE TABLE [dbo].[TBCATEGORIE](
	[IDCATEGORIE] [int] NOT NULL,
	[LIBCATEGORIE] [varchar](50) NULL,
 CONSTRAINT [PK_TBCATEGORIE] PRIMARY KEY NONCLUSTERED 
(
	[IDCATEGORIE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]