CREATE TABLE [dbo].[TBCONGE](
	[IDCONGE] [int] NOT NULL,
	[IDPERSONNEL] [int] NOT NULL,
	[IDTYPECONGE] [int] NOT NULL,
	[MOTIFCONGE] [varchar](100) NULL,
	[DATEDUCONGE] [datetime] NULL,
	[DATEAUCONGE] [datetime] NULL,
	[DATEAUTORISATIONCONGE] [datetime] NULL,
	[DATEDEMANDECONGE] [datetime] NULL,
	[AUTORISECONGE] [bit] NULL,
 CONSTRAINT [PK_TBCONGE] PRIMARY KEY NONCLUSTERED 
(
	[IDCONGE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TBCONGE]  WITH CHECK ADD  CONSTRAINT [FK_TBCONGE_tbPersonnel] FOREIGN KEY([IDPERSONNEL])
REFERENCES [dbo].[TBPERSONNEL] ([IDPERSONNEL])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[TBCONGE] CHECK CONSTRAINT [FK_TBCONGE_tbPersonnel]
GO
ALTER TABLE [dbo].[TBCONGE]  WITH CHECK ADD  CONSTRAINT [FK_TBCONGE_TBTYPECONGE] FOREIGN KEY([IDTYPECONGE])
REFERENCES [dbo].[TBTYPECONGE] ([IDTYPECONGE])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[TBCONGE] CHECK CONSTRAINT [FK_TBCONGE_TBTYPECONGE]