CREATE TABLE [dbo].[TBHEURESUP](
	[IDPERSONNEL] [int] NOT NULL,
	[IDCLIENTADHOC] [int] NOT NULL,
	[DATEHEURESUP] [datetime] NULL,
	[MONTANTHEURESUP] [money] NULL,
	[IDCHEFEQUIPE] [int] NULL,
	[HEUREDEBUTSUP] [datetime] NULL,
	[HEUREFINSUP] [datetime] NULL,
 CONSTRAINT [PK_TBHEURESUP] PRIMARY KEY NONCLUSTERED 
(
	[IDPERSONNEL] ASC,
	[IDCLIENTADHOC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TBHEURESUP]  WITH CHECK ADD  CONSTRAINT [FK_TBHEURESUP_TBCLIENTINTERVENTIONADHOC] FOREIGN KEY([IDCLIENTADHOC])
REFERENCES [dbo].[TBCLIENTINTERVENTIONADHOC] ([IDCLIENTADHOC])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[TBHEURESUP] CHECK CONSTRAINT [FK_TBHEURESUP_TBCLIENTINTERVENTIONADHOC]
GO
ALTER TABLE [dbo].[TBHEURESUP]  WITH CHECK ADD  CONSTRAINT [FK_TBHEURESUP_tbPersonnel] FOREIGN KEY([IDPERSONNEL])
REFERENCES [dbo].[TBPERSONNEL] ([IDPERSONNEL])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[TBHEURESUP] CHECK CONSTRAINT [FK_TBHEURESUP_tbPersonnel]