CREATE TABLE [dbo].[TBPERSONNEL](
	[IDPERSONNEL] [int] NOT NULL,
	[IDQUARTIER] [int] NOT NULL,
	[IDBANQUE] [int] NOT NULL,
	[IDTYPEPID] [int] NOT NULL,
	[IDSEXE] [int] NOT NULL,
	[MATPERSONNEL] [varchar](20) NULL,
	[NOMPERS] [varchar](20) NULL,
	[PRENOMPERS] [varchar](20) NULL,
	[DATENAISPERS] [datetime] NULL,
	[DATERECRUTEMENT] [datetime] NULL,
	[TEL1PERS] [varchar](20) NULL,
	[TEL2PERS] [varchar](20) NULL,
	[ADRESSPERS] [varchar](100) NULL,
	[OBSPERS] [text] NULL,
	[NUMPIDPERS] [varchar](50) NULL,
 CONSTRAINT [PK_TBPERSONNEL] PRIMARY KEY NONCLUSTERED 
(
	[IDPERSONNEL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[TBPERSONNEL]  WITH CHECK ADD  CONSTRAINT [FK_tbPersonnel_TBACCOMPTE] FOREIGN KEY([IDPERSONNEL])
REFERENCES [dbo].[TBACCOMPTE] ([IDACCOMPTE])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[TBPERSONNEL] CHECK CONSTRAINT [FK_tbPersonnel_TBACCOMPTE]
GO
ALTER TABLE [dbo].[TBPERSONNEL]  WITH CHECK ADD  CONSTRAINT [FK_tbPersonnel_TBBANQUE] FOREIGN KEY([IDBANQUE])
REFERENCES [dbo].[TBBANQUE] ([IDBANQUE])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[TBPERSONNEL] CHECK CONSTRAINT [FK_tbPersonnel_TBBANQUE]
GO
ALTER TABLE [dbo].[TBPERSONNEL]  WITH CHECK ADD  CONSTRAINT [FK_tbPersonnel_TBQUARTIER] FOREIGN KEY([IDQUARTIER])
REFERENCES [dbo].[TBQUARTIER] ([IDQUARTIER])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[TBPERSONNEL] CHECK CONSTRAINT [FK_tbPersonnel_TBQUARTIER]
GO
ALTER TABLE [dbo].[TBPERSONNEL]  WITH CHECK ADD  CONSTRAINT [FK_tbPersonnel_TBSEXE] FOREIGN KEY([IDSEXE])
REFERENCES [dbo].[TBSEXE] ([IDSEXE])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[TBPERSONNEL] CHECK CONSTRAINT [FK_tbPersonnel_TBSEXE]
GO
ALTER TABLE [dbo].[TBPERSONNEL]  WITH CHECK ADD  CONSTRAINT [FK_tbPersonnel_TBTYPEPID] FOREIGN KEY([IDTYPEPID])
REFERENCES [dbo].[TBTYPEPID] ([IDTYPEPID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[TBPERSONNEL] CHECK CONSTRAINT [FK_tbPersonnel_TBTYPEPID]