CREATE TABLE [dbo].[TBSALAIRE](
	[IDSALAIRE] [int] NOT NULL,
	[PERIODESALAIRE] [datetime] NULL,
 CONSTRAINT [PK_TBSALAIRE] PRIMARY KEY NONCLUSTERED 
(
	[IDSALAIRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]