CREATE TABLE [dbo].[TBSALAIRE_PERS](
	[IDSALAIRE] [int] NOT NULL,
	[IDPERSONNEL] [int] NOT NULL,
	[IDMODEPAYEMENT] [int] NOT NULL,
	[SBASE] [money] NULL,
	[PRESPO] [money] NULL,
	[FMEDICAUX] [money] NULL,
	[PRATION] [money] NULL,
	[PTRANSPORT] [money] NULL,
	[GRATIF] [money] NULL,
	[PRISQUE] [money] NULL,
	[PDEPART] [money] NULL,
	[PANIERSAL] [money] NULL,
	[HSUP] [money] NULL,
	[CONGEPAYE] [money] NULL,
	[ABSENCES] [money] NULL,
	[ACCOMPTES] [money] NULL,
	[PRETCONSENTI] [money] NULL,
	[CNPS] [money] NULL,
	[IRPP] [money] NULL,
	[FIR] [money] NULL,
	[TAF] [money] NULL,
 CONSTRAINT [PK_TBSALAIRE_PERS] PRIMARY KEY NONCLUSTERED 
(
	[IDSALAIRE] ASC,
	[IDPERSONNEL] ASC,
	[IDMODEPAYEMENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TBSALAIRE_PERS]  WITH CHECK ADD  CONSTRAINT [FK_TBSALAIRE_PERS_TBMODEPAYEMENT] FOREIGN KEY([IDMODEPAYEMENT])
REFERENCES [dbo].[TBMODEPAYEMENT] ([IDMODEPAYEMENT])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[TBSALAIRE_PERS] CHECK CONSTRAINT [FK_TBSALAIRE_PERS_TBMODEPAYEMENT]
GO
ALTER TABLE [dbo].[TBSALAIRE_PERS]  WITH CHECK ADD  CONSTRAINT [FK_TBSALAIRE_PERS_tbPersonnel] FOREIGN KEY([IDPERSONNEL])
REFERENCES [dbo].[TBPERSONNEL] ([IDPERSONNEL])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[TBSALAIRE_PERS] CHECK CONSTRAINT [FK_TBSALAIRE_PERS_tbPersonnel]
GO
ALTER TABLE [dbo].[TBSALAIRE_PERS]  WITH CHECK ADD  CONSTRAINT [FK_TBSALAIRE_PERS_TBSALAIRE] FOREIGN KEY([IDSALAIRE])
REFERENCES [dbo].[TBSALAIRE] ([IDSALAIRE])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[TBSALAIRE_PERS] CHECK CONSTRAINT [FK_TBSALAIRE_PERS_TBSALAIRE]