CREATE TABLE [dbo].[TBVAGUE](
	[IDVAGUE] [int] NOT NULL,
	[LIBVAGUE] [varchar](10) NULL,
 CONSTRAINT [PK_TBVAGUE] PRIMARY KEY NONCLUSTERED 
(
	[IDVAGUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]